[package]
name = "bevy_app"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy_matchbox = "0.11"

game = { path = "../game" }

clap = { version = "*", features = ["derive"] }

[dev-dependencies]
bevy = { version = "0.15", default-features = true }