name: Deploy Signaling app to Github registery

on:
  push:
    branches:
      - main

jobs:
  build-deploy-signaling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Build docker
      run: cd signaling && docker build -t ghcr.io/berlingoqc/p2p-card/p2p-card-signaling:latest .

    - name: Publish docker
      run: docker push ghcr.io/berlingoqc/p2p-card/p2p-card-signaling:latest


  build-deploy-website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Install cargo-make
      run: cargo install cargo-make && cargo install -f wasm-bindgen-cli --version 0.2.97

    - name: Install protoc
      run: sudo apt-get install protobuf-compiler

    - name: Npm install
      run: (cd website/angular && npm install) && (cd website/hugo && npm install)

    - name: Build Hugo Site
      run: (cd website/hugo && npm run build && cat ./public/index.html)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT }}
        publish_dir: ./website/hugo/public/
